const data = [
    {
        responsive_id: '',
        id: 1,
        col_title: 'COSIT',
        col_name: 'College of Science and Technology',
        col_email: 'cosit@tasued.edu.ng',
        col_phone: '08094444444',
        // status: 'Dr. Odulaja',
        status: 1,
    },
    {
        responsive_id: '',
        id: 2,
        col_title: 'COHUM',
        col_name: 'College of Humanities',
        col_email: 'cohum@tasued.edu.ng',
        col_phone: '08074444444',
        // hod_name: 'Dr. Abegijina',
        status: 2,
    },
    {
        responsive_id: '',
        id: 3,
        col_title: 'COSMAS',
        col_name: 'College of Social and Management Science',
        col_email: 'cosmas@tasued.edu.ng',
        col_phone: '08034444444',
        // hod_name: 'Dr. Goodluck',
        status: 1,
    },
    {
        responsive_id: '',
        id: 4,
        col_title: 'COVTED',
        col_name: 'College of Vocational and Technology Education',
        col_email: 'covted@tasued.edu.ng',
        col_phone: '08054444444',
        // hod_name: 'Dr. Chukuemeka',
        status: 2,
    },
    // {
    //     responsive_id: '',
    //     id: 5,
    //     col_title: 'Computer Science',
    //     col_name: 'Chemical Sciences',
    //     col_email: '005',
    //     col_phone: 'chemicalscience@tasued.edu.ng',
    //     // hod_name: 'Dr. Fred Amata',
    //     status: 5,
    // },

]

const search = [
    {
        responsive_id: '',
        id: 1,
        dept_name: 'Computer Science',
        dept_code: '001',
        dept_email: 'computerscience@tasued.edu.ng',
        // hod_name: 'Dr. Odulaja',
        status: 1,
    },
    {
        responsive_id: '',
        id: 2,
        dept_name: 'Mathematics',
        dept_code: '002',
        dept_email: 'mathematics@tasued.edu.ng',
        // hod_name: 'Dr. Abegijina',
        status: 2,
    },
    {
        responsive_id: '',
        id: 3,
        dept_name: 'Biological Science',
        dept_code: '003',
        dept_email: 'biologicalscience@tasued.edu.ng',
        // hod_name: 'Dr. Goodluck',
        status: 2,
    },
    {
        responsive_id: '',
        id: 4,
        dept_name: 'Physics',
        dept_code: '004',
        dept_email: 'physics@tasued.edu.ng',
        // hod_name: 'Dr. Chukuemeka',
        status: 4,
    },
    {
        responsive_id: '',
        id: 5,
        dept_name: 'Chemical Sciences',
        dept_code: '005',
        dept_email: 'chemicalscience@tasued.edu.ng',
        // hod_name: 'Dr. Fred Amata',
        status: 5,
    },

]
export default 
    data;
    search
