const data = [
    {
        responsive_id: '',
        id: 1,
        spec_name: 'Undergraduate',
        prog_name: 'Computer Science',
        sm: 'FT',
        em: 'UTME',
        sl: '100',
        el: '400',
        status: 1,
    },
    {
        responsive_id: '',
        id: 2,
        spec_name: 'Undergraduate',
        prog_name: 'Mathematics',
        sm: 'FT',
        em: 'DE',
        sl: '100',
        el: '400',
        status: 2,
    },
    {
        responsive_id: '',
        id: 3,
        spec_name: 'Undergraduate',
        prog_name: 'Biology',
        sm: 'PT',
        em: 'UTME',
        sl: '100',
        el: '400',
        status: 3,
    },
    {
        responsive_id: '',
        id: 4,
        spec_name: 'Post Graduate',
        prog_name: 'Physics',
        sm: 'FT',
        em: 'Ph.d',
        sl: '600',
        el: '800',
        status: 4,
    },
    {
        responsive_id: '',
        id: 5,
        spec_name: 'Post Graduate',
        prog_name: 'Chemistry',
        sm: 'PT',
        em: 'PG.d',
        sl: '600',
        el: '700',
        status: 5,
    },

]
export default data